language: python

python:
  - "3.5"

env:
  - AWS_SECRET_ACCESS_KEY=fake_key AWS_ACCESS_KEY_ID=fake_id TOX_ENV=py35
  - AWS_SECRET_ACCESS_KEY=fake_key AWS_ACCESS_KEY_ID=fake_id TOX_ENV=flake8

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
